import "./globals.css";
import type { Metadata } from "next";
// import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import { QueryClientProvider } from '@tanstack/react-query';
import queryClient from '../lib/queyClient';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientWrap({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}



