import './globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar/Navbar';
// import { useClient } from 'next/router'; // Import use client for Context API
// import { AuthProvider } from './context'; // Import context

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// @useClient // Mark the component as client-side
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { user } = useContext(AuthContext); // Access context values

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar user={user} /> Pass user data to Navbar if needed */}
        {/* <AuthProvider> Wrap application with context provider */}
          {children}
        {/* </AuthProvider> */}
        <Toaster />
      </body>
    </html>
  );
}
